import os
import logging
import openai
import time
import sys
import json

sys.path.append(os.path.expanduser('~/repos/llm-rank-optimizer'))
from tools import decode_adv_prompt

TWITTER_CHAR_LIMIT = 280
DEFAULT_RESPONSE = "Thanks for sharing your thoughts! I appreciate your perspective."
SYSTEM_PROMPT = """You are a helpful assistant that crafts engaging and relevant replies to tweets.
Your replies should be conversational, contextually appropriate, and under 280 characters.
Avoid generic responses and focus on the specific content of the tweet."""

class STSIntegrator:
    """Handles the integration of Strategic Text Sequences into responses."""
    
    def __init__(self, sts_dir=None):
        """
        Initialize the STS integrator.
        
        Args:
            sts_dir: Directory containing the STS file generated by llm-rank-optimizer
        """
        self.sts = None
        if sts_dir:
            self.load_sts(sts_dir)
    
    def load_sts(self, sts_dir):
        """Load a Strategic Text Sequence from a directory."""
        try:
            sts_path = os.path.join(os.path.expanduser(sts_dir), "sts.txt")
            if os.path.exists(sts_path):
                with open(sts_path, 'r') as file:
                    self.sts = file.read().strip()
                return True
            else:
                logging.warning(f"STS file not found at {sts_path}")
        except Exception as e:
            logging.error(f"Error loading STS: {str(e)}")
        return False
    
    def apply_sts(self, content):
        """Apply the STS to the content if available."""
        if not self.sts:
            return content
            
        try:
            json_data = json.loads(self.sts)
            if 'Description' in json_data:
                sts_text = json_data['Description']
                return f"{content} {sts_text}"
        except:
            return f"{content} {self.sts}"

def generate_response(tweet_text, max_retries=3, model="gpt-4", sts_integrator=None):
    """
    Generate a response to a tweet using OpenAI's GPT models.
    
    Args:
        tweet_text: The text of the tweet to respond to
        max_retries: Maximum number of retries on API failure
        model: The GPT model to use
        sts_integrator: Optional STSIntegrator to enhance responses
        
    Returns:
        A string containing the generated response
    """
    openai.api_key = os.getenv('OPENAI_API_KEY')
    
    system_prompt = SYSTEM_PROMPT
    user_prompt = tweet_text
    
    if sts_integrator:
        system_prompt = sts_integrator.apply_sts(system_prompt)
    
    for attempt in range(max_retries):
        try:
            response = openai.ChatCompletion.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Generate a reply to this tweet: {user_prompt}"}
                ],
                max_tokens=100,
                temperature=0.7
            )
            
            reply_text = response.choices[0].message.content.strip()
            
            if len(reply_text) > TWITTER_CHAR_LIMIT:
                reply_text = reply_text[:TWITTER_CHAR_LIMIT - 3] + "..."
                
            return reply_text
            
        except Exception as e:
            logging.error(f"Error generating response (attempt {attempt+1}/{max_retries}): {str(e)}")
            if attempt < max_retries - 1:
                sleep_time = (2 ** attempt) + 1
                logging.info(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                logging.error("Max retries reached. Using default response.")
                return DEFAULT_RESPONSE
